name: 'Update Bronze Layer Google Drive'
description: 'Update Bronze Layer using SUS file type and group'
author: 'Heber A. Scachetti'
inputs:
  sus_file_group:
    description: 'SUS File Group'
    required: true
  sus_file_type:
    description: 'SUS File Type'
    required: true
  gd_credentials:
    description: 'Credenciais GCP'
    required: true
  max_files:
    description: 'Número máximo de arquivos a serem processados'
    required: true
  max_time:
    description: 'Tempo máximo de processamento de arquivos (segundos)'
    required: true
  google_raw_drive_id:
    description: 'google team driver raw id'
    required: true    
    
runs:
  using: 'composite'
  steps:
    - run: echo "🎉 The job was triggered by a ${{ github.event_name }} event."
      shell: bash
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
      shell: bash
    - name: 'google-auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ inputs.gd_credentials }}
    - name: Download and prepare Spark
      run: |
        echo "running script"
        export REPO_ROOT_FOLDER=/home/runner/work/sus-kpis-analysis
        export DATALAKE_PREFIX=${REPO_ROOT_FOLDER}/datalake
        echo $REPO_ROOT_FOLDER
        echo $DATALAKE_PREFIX        

        echo "spark setup"
        export PYTHONHASHSEED=1234
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        export SPARK_HOME=$REPO_ROOT_FOLDER/spark-3.4.2-bin-hadoop3
        export SPARK_VERSION=3.4.2

        export GOOGLE_RAW_DRIVE_ID=${{ inputs.google_raw_drive_id }}        
        export SUS_FILE_GROUP=${{ inputs.sus_file_group }}
        export SUS_FILE_TYPE=${{ inputs.sus_file_type }}
        export MAX_FILES=${{ inputs.max_files }}          
        export MAX_TIME=${{ inputs.max_time }}
        python3 $REPO_ROOT_FOLDER/sus-kpis-analysis/sia/etls/update-datasus-bronze-layer-google-drive.py
      shell: bash
    - run: echo "🍏 This job's status is ${{ job.status }}." 
      shell: bash
    - uses: gautamkrishnar/keepalive-workflow@v1 # using the workflow with default settings
