name: Create Cancer MAMA DB
run-name: ${{ github.actor }} is  Create Cancer MAMA DB 🚀
on: 
  workflow_dispatch:
jobs:
  update-bronze-layer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Install spark and mount team google drive
      uses: ./.github/actions/prepare-deltalake
      with:
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        google_bronze_drive_id: ${{ secrets.GOOGLE_BRONZE_DRIVE_ID }}
        google_silver_drive_id: ${{ secrets.GOOGLE_SILVER_DRIVE_ID }}
        google_gold_drive_id: ${{ secrets.GOOGLE_GOLD_DRIVE_ID }}
        service_account_user: ${{ secrets.SERVICE_ACCOUNT_USER }}
       
  
  keepalive-job:
    name: Keepalive Workflow
    if: ${{ always() }}
    needs: update-bronze-layer
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          use_api: false
