name: Create Cancer MAMA DB
run-name: ${{ github.actor }} is  Create Cancer MAMA DB 🚀
on: 
  workflow_dispatch:     
  schedule:
    - cron:  '0 16 * * 1'
jobs:
  prepare-deltalake-and-create-cancer-mama-db:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Install spark and mount team google drive
      uses: ./.github/actions/prepare-deltalake
      with:
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        google_bronze_drive_id: ${{ secrets.GOOGLE_BRONZE_DRIVE_ID }}
        google_silver_drive_id: ${{ secrets.GOOGLE_SILVER_DRIVE_ID }}
        google_gold_drive_id: ${{ secrets.GOOGLE_GOLD_DRIVE_ID }}
        service_account_user: ${{ secrets.SERVICE_ACCOUNT_USER }}

    - name: Run ETL to Create Mama Cancer        
      run: |
        echo "running script"
        export REPO_ROOT_FOLDER=${{ github.workspace }}
        export DATALAKE_PREFIX=${REPO_ROOT_FOLDER}/datalake
        echo $REPO_ROOT_FOLDER
        echo $DATALAKE_PREFIX        

        echo "spark setup"
        export PYTHONHASHSEED=1234
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        export SPARK_HOME=$REPO_ROOT_FOLDER/spark-3.5.5-bin-hadoop3
        export SPARK_VERSION=3.5.5
        python3 $REPO_ROOT_FOLDER/sia/etls/cancer-mama-db.py


  
  workflow-keepalive:
    if: github.event_name == 'schedule'
    needs: prepare-deltalake-and-create-cancer-mama-db
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
