name: Update Bronze Layer CNES Wave 2 (LT, PF, RC, SR)
run-name: ${{ github.actor }} is  Update Bronze Layer CNES Wave 2 (LT, PF, RC, SR) 🚀
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 6'
jobs:
  update-bronze-layer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Install spark and mount team google drive
      uses: ./.github/actions/prepare-bronze-layer
      with:
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        google_bronze_drive_id: ${{ secrets.GOOGLE_BRONZE_DRIVE_ID }}
        google_raw_drive_id: ${{ secrets.GOOGLE_RAW_DRIVE_ID }}
        service_account_user: ${{ secrets.SERVICE_ACCOUNT_USER }}

    - name: Updating CNES LT delta Table
      uses: ./.github/actions/update-bronze-layer-google-drive
      with:
        sus_file_group: 'CNES'
        sus_file_type: 'LT'
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        max_files: '1000'
        max_time: '4800'
        google_raw_drive_id: ${{ secrets.GOOGLE_RAW_DRIVE_ID }}  

    - name: Updating CNES PF delta Table
      uses: ./.github/actions/update-bronze-layer-google-drive
      with:
        sus_file_group: 'CNES'
        sus_file_type: 'PF'
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        max_files: '1000'
        max_time: '4800'
        google_raw_drive_id: ${{ secrets.GOOGLE_RAW_DRIVE_ID }}       

    - name: Updating CNES RC delta Table
      uses: ./.github/actions/update-bronze-layer-google-drive
      with:
        sus_file_group: 'CNES'
        sus_file_type: 'RC'
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        max_files: '1000'
        max_time: '4800'
        google_raw_drive_id: ${{ secrets.GOOGLE_RAW_DRIVE_ID }}       

    - name: Updating CNES SR delta Table
      uses: ./.github/actions/update-bronze-layer-google-drive
      with:
        sus_file_group: 'CNES'
        sus_file_type: 'SR'
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        max_files: '1000'
        max_time: '4800'
        google_raw_drive_id: ${{ secrets.GOOGLE_RAW_DRIVE_ID }}
  
  workflow-keepalive:
    if: github.event_name == 'schedule'
    needs: update-bronze-layer
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
