name: Update Bronze Layer SIH-RD
run-name: ${{ github.actor }} is  Update Bronze Layer SIH-RD 🚀
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 1'
jobs:
  update-bronze-layer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Install spark and mount team google drive
      uses: ./.github/actions/prepare-bronze-layer
      with:
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        google_bronze_drive_id: ${{ secrets.GOOGLE_BRONZE_DRIVE_ID }}
        google_raw_drive_id: ${{ secrets.GOOGLE_RAW_DRIVE_ID }}
        service_account_user: ${{ secrets.SERVICE_ACCOUNT_USER }}

    - name: Updating SIH RD delta Table
      uses: ./.github/actions/update-bronze-layer-google-drive
      with:
        sus_file_group: 'SIH'
        sus_file_type: 'RD'
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        max_files: '1000'
        max_time: '18000'
        google_raw_drive_id: ${{ secrets.GOOGLE_RAW_DRIVE_ID }}        
  
  workflow-keepalive:
    if: github.event_name == 'schedule'
    needs: update-bronze-layer
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
