name: Update Bronze Layer SIA (AM e BI)
run-name: ${{ github.actor }} is  Update Bronze Layer SIA (AM e BI) 🚀
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 3'
jobs:
  update-bronze-layer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Install spark and mount team google drive
      uses: ./.github/actions/prepare-bronze-layer
      with:
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        google_bronze_drive_id: ${{ secrets.GOOGLE_BRONZE_DRIVE_ID }}
        google_raw_drive_id: ${{ secrets.GOOGLE_RAW_DRIVE_ID }}
        service_account_user: ${{ secrets.SERVICE_ACCOUNT_USER }}

    - name: Updating SIA BI delta Table
      uses: ./.github/actions/update-bronze-layer-google-drive
      with:
        sus_file_group: 'SIA'
        sus_file_type: 'BI'
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        max_files: '1000'
        max_time: '9000'
        google_raw_drive_id: ${{ secrets.GOOGLE_RAW_DRIVE_ID }}

    - name: Updating SIA BI delta Table
      uses: ./.github/actions/update-bronze-layer-google-drive
      with:
        sus_file_group: 'SIA'
        sus_file_type: 'AM'
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        max_files: '1000'
        max_time: '9000'
        google_raw_drive_id: ${{ secrets.GOOGLE_RAW_DRIVE_ID }}
  
  keepalive-job:
    name: Keepalive Workflow
    if: ${{ always() }}
    needs: update-bronze-layer
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          use_api: false
