name: Update Bronze Layer CNES Wave 1 (DC, EP, EQ, HB, IN)
run-name: ${{ github.actor }} is  Update Bronze Layer CNES Files Wave 1 (DC, EP, EQ, HB, IN) 🚀
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  update-bronze-layer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Install spark and mount team google drive
      uses: ./.github/actions/prepare-bronze-layer
      with:
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        google_bronze_drive_id: ${{ secrets.GOOGLE_BRONZE_DRIVE_ID }}
        google_raw_drive_id: ${{ secrets.GOOGLE_RAW_DRIVE_ID }}
        service_account_user: ${{ secrets.SERVICE_ACCOUNT_USER }}

    - name: Updating CNES DC delta Table
      uses: ./.github/actions/update-bronze-layer-google-drive
      with:
        sus_file_group: 'CNES'
        sus_file_type: 'DC'
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        max_files: '1000'
        max_time: '4200'
        google_raw_drive_id: ${{ secrets.GOOGLE_RAW_DRIVE_ID }}  

    - name: Updating CNES EP delta Table
      uses: ./.github/actions/update-bronze-layer-google-drive
      with:
        sus_file_group: 'CNES'
        sus_file_type: 'EP'
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        max_files: '1000'
        max_time: '4200'
        google_raw_drive_id: ${{ secrets.GOOGLE_RAW_DRIVE_ID }}

    - name: Updating CNES EQ delta Table
      uses: ./.github/actions/update-bronze-layer-google-drive
      with:
        sus_file_group: 'CNES'
        sus_file_type: 'EQ'
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        max_files: '1000'
        max_time: '4200'
        google_raw_drive_id: ${{ secrets.GOOGLE_RAW_DRIVE_ID }}       

    - name: Updating CNES HB delta Table
      uses: ./.github/actions/update-bronze-layer-google-drive
      with:
        sus_file_group: 'CNES'
        sus_file_type: 'HB'
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        max_files: '1000'
        max_time: '4200'
        google_raw_drive_id: ${{ secrets.GOOGLE_RAW_DRIVE_ID }}

    - name: Updating CNES IN delta Table
      uses: ./.github/actions/update-bronze-layer-google-drive
      with:
        sus_file_group: 'CNES'
        sus_file_type: 'IN'
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        max_files: '1000'
        max_time: '4200'
        google_raw_drive_id: ${{ secrets.GOOGLE_RAW_DRIVE_ID }}
