name: Update Bronze Layer SIA-AQ-AR
run-name: ${{ github.actor }} is  Update Bronze Layer SIA-AQ-AR 🚀
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  update-bronze-layer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Install spark and mount team google drive
      uses: ./.github/actions/prepare-bronze-layer
      with:
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        google_bronze_drive_id: ${{ secrets.GOOGLE_BRONZE_DRIVE_ID }}
        google_raw_drive_id: ${{ secrets.GOOGLE_RAW_DRIVE_ID }}
        service_account_user: ${{ secrets.SERVICE_ACCOUNT_USER }}

    - name: Updating SIA-AQ delta Table
      uses: ./.github/actions/update-bronze-layer-google-drive
      with:
        sus_file_group: 'SIA'
        sus_file_type: 'AQ'
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        max_files: '1000'
        max_time: '9000'
        google_bronze_drive_id: ${{ secrets.GOOGLE_BRONZE_DRIVE_ID }}


    - name: Updating SIA-AR delta Table
      uses: ./.github/actions/update-bronze-layer-google-drive
      with:
        sus_file_group: 'SIA'
        sus_file_type: 'AR'
        gd_credentials: ${{ secrets.GD_CREDENTIALS }}
        max_files: '1000'
        max_time: '9000'
        google_bronze_drive_id: ${{ secrets.GOOGLE_BRONZE_DRIVE_ID }}
        
