name: Update Bronze Layer CNES Wave 2 (LT, PF, RC, SR)
run-name: ${{ github.actor }} is  Update Bronze Layer CNES Wave 2 (LT, PF, RC, SR) 🚀
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'  

jobs:
  update-bronze-layer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Update Bronze Layer CNES LT
      uses: ./.github/actions/update-bronze-layer
      with:
        sus_file_group: 'CNES'
        sus_file_type: 'LT'
        gcp_credentials: ${{ secrets.GCP_CREDENTIALS }} 
        max_files: '1000'
        max_time: '5400'        

    - name: Update Bronze Layer CNES PF
      uses: ./.github/actions/update-bronze-layer
      with:
        sus_file_group: 'CNES'
        sus_file_type: 'PF'
        gcp_credentials: ${{ secrets.GCP_CREDENTIALS }} 
        max_files: '1000'
        max_time: '5400'        

    - name: Update Bronze Layer CNES RC
      uses: ./.github/actions/update-bronze-layer
      with:
        sus_file_group: 'CNES'
        sus_file_type: 'RC'
        gcp_credentials: ${{ secrets.GCP_CREDENTIALS }} 
        max_files: '1000'
        max_time: '5400'        

    - name: Update Bronze Layer CNES SR
      uses: ./.github/actions/update-bronze-layer
      with:
        sus_file_group: 'CNES'
        sus_file_type: 'SR'
        gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}      
        max_files: '1000'
        max_time: '5400'        
